/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.admin_panales.add_users;
import GUI.admin_panales.report_JPanel;
import GUI.admin_panales.search_users_JPanel;
import GUI.admin_panales.spots_JPanel;
import java.awt.GridBagConstraints;

/**
 *
 * @author Ramy
 */
public class admin_JFrame extends javax.swing.JFrame {
    add_users u1 ;
    search_users_JPanel d1 ;
    spots_JPanel s ;
    report_JPanel rr ;
    /**
     * Creates new form admin_JFrame
     */
    public admin_JFrame() {
        initComponents();
        setTitle("admin");
        setLocation(430,130);
        setSize(515,585);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0 ;
        c.gridy = 0 ;
        rr = new report_JPanel();
        u1 = new add_users();
        d1 = new search_users_JPanel();
        s = new spots_JPanel();
        admin_dinamic_Panel.add(u1, c);
        admin_dinamic_Panel.add(rr, c);
        admin_dinamic_Panel.add(d1, c);
        admin_dinamic_Panel.add(s, c);
         u1.setVisible(false);
         d1.setVisible(false);
         s.setVisible(false);
         rr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_blue_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin_static_Panel1 = new javax.swing.JPanel();
        add_Button = new javax.swing.JButton();
        delete_Button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        admin_dinamic_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_blue_panel.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("welcome si");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/settings.png"))); // NOI18N

        javax.swing.GroupLayout admin_blue_panelLayout = new javax.swing.GroupLayout(admin_blue_panel);
        admin_blue_panel.setLayout(admin_blue_panelLayout);
        admin_blue_panelLayout.setHorizontalGroup(
            admin_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_blue_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        admin_blue_panelLayout.setVerticalGroup(
            admin_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_blue_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(admin_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(admin_blue_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        admin_static_Panel1.setBackground(new java.awt.Color(204, 204, 204));

        add_Button.setBackground(new java.awt.Color(51, 153, 255));
        add_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_Button.setText("add users");
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });

        delete_Button.setBackground(new java.awt.Color(51, 153, 255));
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setText("find users");
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("spots");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("create report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admin_static_Panel1Layout = new javax.swing.GroupLayout(admin_static_Panel1);
        admin_static_Panel1.setLayout(admin_static_Panel1Layout);
        admin_static_Panel1Layout.setHorizontalGroup(
            admin_static_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_static_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(admin_static_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        admin_static_Panel1Layout.setVerticalGroup(
            admin_static_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_static_Panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(add_Button)
                .addGap(36, 36, 36)
                .addComponent(delete_Button)
                .addGap(44, 44, 44)
                .addComponent(jButton4)
                .addGap(46, 46, 46)
                .addComponent(jButton5)
                .addGap(53, 53, 53)
                .addComponent(jButton6)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(admin_static_Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 420));

        admin_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(admin_dinamic_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 370, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        // TODO add your handling code here:
        u1.setVisible(true);
        rr.setVisible(false);
        s.setVisible(false);
        d1.setVisible(false);
    }//GEN-LAST:event_add_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
        u1.setVisible(false);
        d1.setVisible(true);
        rr.setVisible(false);
        s.setVisible(false);
        
       
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Home return2 = new Home();
        return2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        s.setVisible(true);
        u1.setVisible(false);
        d1.setVisible(false);
        rr.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        rr.setVisible(true);
        s.setVisible(false);
        u1.setVisible(false);
        d1.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JPanel admin_blue_panel;
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JPanel admin_static_Panel1;
    private javax.swing.JButton delete_Button;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
