/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.guest_panels.bill_JPanel;
import GUI.guest_panels.spots_JPanel ;
import java.awt.GridBagConstraints;

/**
 *
 * @author Ramy
 */
public class guest_JFrame extends javax.swing.JFrame {
    spots_JPanel df ;
    bill_JPanel pf ;
    /**
     * Creates new form guest_JFrame
     */
    public guest_JFrame() {
        initComponents();
        setTitle("quest");
        setLocation(430,130);
        setSize(515,585);
        df = new spots_JPanel();
        pf = new bill_JPanel();
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0 ;
        c.gridy = 0 ;
        guest_dinamic_Panel.add(df, c);
        guest_dinamic_Panel.add(pf, c);
        df.setVisible(false);
        pf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        guest_blue_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guest_dinamic_Panel = new javax.swing.JPanel();
        admin_dinamic_Panel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        empty_parck_picture = new javax.swing.JLabel();
        one_parcked_car_picture = new javax.swing.JLabel();
        two_parcked_cars_picture = new javax.swing.JLabel();
        three_parcked_cars_picture = new javax.swing.JLabel();
        four_parcked_cars_picture = new javax.swing.JLabel();
        five_parcked_cars_picture = new javax.swing.JLabel();
        six_parcked_cars_picture = new javax.swing.JLabel();
        seven_parcked_cars_picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guest_blue_panel.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("welcome si");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parked-car.png"))); // NOI18N

        javax.swing.GroupLayout guest_blue_panelLayout = new javax.swing.GroupLayout(guest_blue_panel);
        guest_blue_panel.setLayout(guest_blue_panelLayout);
        guest_blue_panelLayout.setHorizontalGroup(
            guest_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_blue_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        guest_blue_panelLayout.setVerticalGroup(
            guest_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_blue_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guest_blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(guest_blue_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        guest_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        guest_dinamic_Panel.setLayout(new java.awt.GridBagLayout());

        admin_dinamic_Panel4.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel4.setLayout(new java.awt.GridBagLayout());

        jButton5.setText("print ticket");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 140, 17, 0);
        admin_dinamic_Panel4.add(jButton5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        admin_dinamic_Panel4.add(empty_parck_picture, gridBagConstraints);

        one_parcked_car_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/one_parcked_car.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(one_parcked_car_picture, gridBagConstraints);

        two_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/two_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(two_parcked_cars_picture, gridBagConstraints);

        three_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/three_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(three_parcked_cars_picture, gridBagConstraints);

        four_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/four_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(four_parcked_cars_picture, gridBagConstraints);

        five_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/five_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(five_parcked_cars_picture, gridBagConstraints);

        six_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/six_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(six_parcked_cars_picture, gridBagConstraints);

        seven_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/7_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(seven_parcked_cars_picture, gridBagConstraints);

        guest_dinamic_Panel.add(admin_dinamic_Panel4, new java.awt.GridBagConstraints());

        getContentPane().add(guest_dinamic_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guest_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guest_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guest_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guest_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guest_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_dinamic_Panel4;
    private javax.swing.JLabel empty_parck_picture;
    private javax.swing.JLabel five_parcked_cars_picture;
    private javax.swing.JLabel four_parcked_cars_picture;
    private javax.swing.JPanel guest_blue_panel;
    private javax.swing.JPanel guest_dinamic_Panel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel one_parcked_car_picture;
    private javax.swing.JLabel seven_parcked_cars_picture;
    private javax.swing.JLabel six_parcked_cars_picture;
    private javax.swing.JLabel three_parcked_cars_picture;
    private javax.swing.JLabel two_parcked_cars_picture;
    // End of variables declaration//GEN-END:variables
}
