/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ramy
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTitle("home");
        setLocation(430,130);
        setSize(515,585);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quick_parck_button1 = new javax.swing.JButton();
        signup_button = new javax.swing.JButton();
        login_button = new javax.swing.JButton();
        elgarash_label = new javax.swing.JLabel();
        home_icon = new javax.swing.JLabel();
        car_picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quick_parck_button1.setBackground(new java.awt.Color(0, 0, 0));
        quick_parck_button1.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        quick_parck_button1.setForeground(new java.awt.Color(255, 255, 255));
        quick_parck_button1.setText("Quick Parking");
        quick_parck_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quick_parck_button1ActionPerformed(evt);
            }
        });
        getContentPane().add(quick_parck_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 210, 40));

        signup_button.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        signup_button.setText("Sign uP");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signup_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 150, 40));

        login_button.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        login_button.setText("LOG IN");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 150, 40));

        elgarash_label.setFont(new java.awt.Font("Vivaldi", 3, 100)); // NOI18N
        elgarash_label.setForeground(new java.awt.Color(255, 255, 255));
        elgarash_label.setText("  el garash");
        getContentPane().add(elgarash_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 130));

        home_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/home (1).png"))); // NOI18N
        getContentPane().add(home_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 80));

        car_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/32da914982d9dbd9c25263791a0b39b4--girl-car-car-girls.jpg"))); // NOI18N
        getContentPane().add(car_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        login_JFrame x = new login_JFrame();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        signup_JFrame n = new signup_JFrame();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void quick_parck_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quick_parck_button1ActionPerformed
        // TODO add your handling code here:
        quick_parck_JFrame qp = new quick_parck_JFrame();
        qp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_quick_parck_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car_picture;
    private javax.swing.JLabel elgarash_label;
    private javax.swing.JLabel home_icon;
    private javax.swing.JButton login_button;
    private javax.swing.JButton quick_parck_button1;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
