/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classes.EntryStation;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramy
 */
public class quick_parck_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form quick_parck_JFrame
     */
    public quick_parck_JFrame() {
        initComponents();
        setTitle("Quick Park");
        setLocation(430,130);
        setSize(515,585);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        entry_station_Button = new javax.swing.JButton();
        exit_station_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_button.setBackground(new java.awt.Color(0, 0, 0));
        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/login.png"))); // NOI18N
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramy\\Downloads\\barrier-and-car (1).png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 140));

        entry_station_Button.setFont(new java.awt.Font("Aldhabi", 3, 36)); // NOI18N
        entry_station_Button.setText("Entry Station");
        entry_station_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry_station_ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(entry_station_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 190, 40));

        exit_station_Button.setFont(new java.awt.Font("Aldhabi", 3, 36)); // NOI18N
        exit_station_Button.setText("Exit Station");
        exit_station_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_station_ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(exit_station_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramy\\Downloads\\Parking.jpg")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 500));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entry_station_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry_station_ButtonActionPerformed
        // TODO add your handling code here:
        if (EntryStation.isParkingEmpty() == 0){
        entry_station_JFrame es = new entry_station_JFrame();
        es.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"There are no Empty Parking");
        }
    }//GEN-LAST:event_entry_station_ButtonActionPerformed

    private void exit_station_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_station_ButtonActionPerformed
        // TODO add your handling code here: 
        
        exit_station1_JFrame es = new exit_station1_JFrame();
        es.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit_station_ButtonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Home back = new Home() ;
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quick_parck_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quick_parck_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quick_parck_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quick_parck_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quick_parck_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton entry_station_Button;
    private javax.swing.JButton exit_station_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
