/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.admin_panales;

/**
 *
 * @author Ramy
 */
public class report_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form report_JPanel
     */
    public report_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_dinamic_Panel = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        admin_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        admin_dinamic_Panel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 120, -1));
        admin_dinamic_Panel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, -1));
        admin_dinamic_Panel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 120, -1));

        jLabel2.setText("number of customer");
        admin_dinamic_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        jLabel3.setText("avilalble spots");
        admin_dinamic_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setText("shift money");
        admin_dinamic_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_dinamic_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin_dinamic_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
