/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.admin_panales;

import classes.Customer;
import java.awt.GridBagConstraints;
import javax.swing.JTextField;


/**
 *
 * @author Ramy
 */
public class search_users_JPanel extends javax.swing.JPanel {
    /**
     * Creates new form search_users_JPanel
     */
    public search_users_JPanel() {
        initComponents();
       jLabel2.setVisible(false);
       jLabel3.setVisible(false);
       jPanel2.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_dinamic_Panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        PlateNumber_TextField2 = new javax.swing.JTextField();
        ID_TextField3 = new javax.swing.JTextField();
        use_name_Label2 = new javax.swing.JLabel();
        use_icon2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        use_icon = new javax.swing.JLabel();
        use_name_Label = new javax.swing.JLabel();
        use_name_Label1 = new javax.swing.JLabel();
        use_icon1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        admin_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        admin_dinamic_Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        admin_dinamic_Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 271, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlateNumber_TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateNumber_TextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(PlateNumber_TextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, 28));

        ID_TextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(ID_TextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 161, 28));

        use_name_Label2.setFont(new java.awt.Font("Aldhabi", 2, 24)); // NOI18N
        use_name_Label2.setForeground(new java.awt.Color(51, 153, 255));
        use_name_Label2.setText("ID");
        jPanel2.add(use_name_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        use_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/user.png"))); // NOI18N
        use_icon2.setText("jLabel5");
        jPanel2.add(use_icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 31, 42));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 206, 10));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator4.setAlignmentX(1.0F);
        jSeparator4.setAlignmentY(1.0F);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 206, 10));

        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator5.setAlignmentX(1.0F);
        jSeparator5.setAlignmentY(1.0F);
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 206, 10));
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, 29));

        use_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/key.png"))); // NOI18N
        use_icon.setText("jLabel5");
        jPanel2.add(use_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 31, 42));

        use_name_Label.setFont(new java.awt.Font("Aldhabi", 2, 24)); // NOI18N
        use_name_Label.setForeground(new java.awt.Color(51, 153, 255));
        use_name_Label.setText("password");
        jPanel2.add(use_name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 30));

        use_name_Label1.setFont(new java.awt.Font("Aldhabi", 2, 24)); // NOI18N
        use_name_Label1.setForeground(new java.awt.Color(51, 153, 255));
        use_name_Label1.setText("plate number");
        jPanel2.add(use_name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));

        use_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/license-plate (1).png"))); // NOI18N
        jPanel2.add(use_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 40));

        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel2.setText("user deleted successfuly");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, -1));

        jLabel3.setText("user updated  successfuly");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 20));

        admin_dinamic_Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(admin_dinamic_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(admin_dinamic_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Customer x = new Customer();
        x.SerachCustomer(Integer.parseInt(jTextField1.getText()));
        ID_TextField3.setText("" +x.Cid);
        PlateNumber_TextField2.setText("" + x.Cplate);
        jPanel2.setVisible(true);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PlateNumber_TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateNumber_TextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateNumber_TextField2ActionPerformed

    private void ID_TextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jPanel2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_TextField3;
    private javax.swing.JTextField PlateNumber_TextField2;
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel use_icon;
    private javax.swing.JLabel use_icon1;
    private javax.swing.JLabel use_icon2;
    private javax.swing.JLabel use_name_Label;
    private javax.swing.JLabel use_name_Label1;
    private javax.swing.JLabel use_name_Label2;
    // End of variables declaration//GEN-END:variables
}
