/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.user_panels;

/**
 *
 * @author Ramy
 */
public class account_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form account_JPanel
     */
    public account_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        admin_dinamic_Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("conform");
        admin_dinamic_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 90, -1));

        jButton2.setText("cancel");
        admin_dinamic_Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 360, 80, -1));

        jLabel1.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("name");
        admin_dinamic_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 40));

        jLabel2.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("password");
        admin_dinamic_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jLabel3.setFont(new java.awt.Font("Aldhabi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("plate number");
        admin_dinamic_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 30));

        jTextField1.setText("ramy hesham");
        admin_dinamic_Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 30));

        jTextField2.setText("ك ع م 1 4 7");
        admin_dinamic_Panel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 200, 30));

        jPasswordField1.setText("jPasswordField1");
        admin_dinamic_Panel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/user.png"))); // NOI18N
        admin_dinamic_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/key.png"))); // NOI18N
        admin_dinamic_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/license-plate.png"))); // NOI18N
        admin_dinamic_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/settings (1).png"))); // NOI18N
        admin_dinamic_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 58));

        add(admin_dinamic_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
