/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.user_panels;

import java.awt.GridBagConstraints;

/**
 *
 * @author Ramy
 */
public class pre_bill_JPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form pre_bill_JPanel
     */
    public pre_bill_JPanel() {
        initComponents();
        admin_dinamic_Panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_dinamic_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        admin_dinamic_Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        user_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        user_dinamic_Panel.setEnabled(false);
        user_dinamic_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Aldhabi", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText(" enter the ticket id");
        user_dinamic_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        user_dinamic_Panel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jButton3.setText("ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        user_dinamic_Panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        admin_dinamic_Panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("payment");
        admin_dinamic_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel1.setText("entry hour");
        admin_dinamic_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, 55, 26));

        jLabel2.setText("exit Hour");
        admin_dinamic_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 127, 55, 26));

        jLabel4.setText("parck time");
        admin_dinamic_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 159, 55, 26));

        jLabel5.setText("coast");
        admin_dinamic_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 55, 23));

        jTextField1.setEditable(false);
        jTextField1.setText("8:30");
        admin_dinamic_Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 96, 190, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("11:30");
        admin_dinamic_Panel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 133, 190, -1));

        jTextField4.setEditable(false);
        jTextField4.setText("3");
        admin_dinamic_Panel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 165, 190, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("5 $");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        admin_dinamic_Panel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/home.png"))); // NOI18N
        admin_dinamic_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 70));

        user_dinamic_Panel.add(admin_dinamic_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 360, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user_dinamic_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user_dinamic_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        admin_dinamic_Panel.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel user_dinamic_Panel;
    // End of variables declaration//GEN-END:variables

    
}
