/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.guest_panels;

/**
 *
 * @author Ramy
 */
public class spots_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form spots_JPanel
     */
    public spots_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        admin_dinamic_Panel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        empty_parck_picture = new javax.swing.JLabel();
        one_parcked_car_picture = new javax.swing.JLabel();
        two_parcked_cars_picture = new javax.swing.JLabel();
        three_parcked_cars_picture = new javax.swing.JLabel();
        four_parcked_cars_picture = new javax.swing.JLabel();
        five_parcked_cars_picture = new javax.swing.JLabel();
        six_parcked_cars_picture = new javax.swing.JLabel();
        seven_parcked_cars_picture = new javax.swing.JLabel();

        admin_dinamic_Panel4.setBackground(new java.awt.Color(255, 255, 255));
        admin_dinamic_Panel4.setLayout(new java.awt.GridBagLayout());

        jButton5.setText("print ticket");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 140, 17, 0);
        admin_dinamic_Panel4.add(jButton5, gridBagConstraints);

        empty_parck_picture.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramy\\Desktop\\parcked_cars\\empty_parck.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        admin_dinamic_Panel4.add(empty_parck_picture, gridBagConstraints);

        one_parcked_car_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/one_parcked_car.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(one_parcked_car_picture, gridBagConstraints);

        two_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/two_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(two_parcked_cars_picture, gridBagConstraints);

        three_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/three_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(three_parcked_cars_picture, gridBagConstraints);

        four_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/four_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(four_parcked_cars_picture, gridBagConstraints);

        five_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/five_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(five_parcked_cars_picture, gridBagConstraints);

        six_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/six_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(six_parcked_cars_picture, gridBagConstraints);

        seven_parcked_cars_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/parcked_cars/7_parcked_cars.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        admin_dinamic_Panel4.add(seven_parcked_cars_picture, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin_dinamic_Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_dinamic_Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_dinamic_Panel;
    private javax.swing.JPanel admin_dinamic_Panel1;
    private javax.swing.JPanel admin_dinamic_Panel2;
    private javax.swing.JPanel admin_dinamic_Panel3;
    private javax.swing.JPanel admin_dinamic_Panel4;
    private javax.swing.JLabel empty_parck_picture;
    private javax.swing.JLabel five_parcked_cars_picture;
    private javax.swing.JLabel four_parcked_cars_picture;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel one_parcked_car_picture;
    private javax.swing.JLabel seven_parcked_cars_picture;
    private javax.swing.JLabel six_parcked_cars_picture;
    private javax.swing.JLabel three_parcked_cars_picture;
    private javax.swing.JLabel two_parcked_cars_picture;
    // End of variables declaration//GEN-END:variables
}
